import path from 'node:path';

export function escapeHTML(value) {
  return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
}

// STUDY: 모든 경로는 현재 페이지에서 계산한다. GitHub Pages의 /WoozyLab/ 접두사와 로컬 미리보기를 함께 지원한다.
export function relativeURL(route, target) {
  if (/^(https:|mailto:)/.test(target)) return target;
  const [pathname, hash] = target.split('#');
  const relative = path.posix.relative(route || '.', pathname || '.') || '.';
  const suffix = path.posix.extname(pathname || '') ? '' : '/';
  return `${relative.startsWith('.') ? relative : './' + relative}${suffix}${hash ? '#' + hash : ''}`;
}

export function appRoute(app, role = '', locale = 'ko') {
  // 검증된 영어 상세 페이지가 없는 앱은 한국어 페이지로 안내한다.
  return `${locale === 'en' && app.slug === 'keypic' ? 'en/' : ''}${app.slug}/${role ? role + '/' : ''}`;
}

export function layout({route, locale = 'ko', title, description, content, site, app, role = '', cssVersion}) {
  const english = locale === 'en';
  const base = english ? 'en/' : '';
  const url = target => escapeHTML(relativeURL(route, target));
  const link = (target, text, extra = '') => `<a href="${url(target)}"${target === route ? ' aria-current="page"' : ''}${extra}>${text}</a>`;
  const hasAlternate = !app || app.slug === 'keypic';
  const alternate = english ? route.replace(/^en\//, '') : `en/${route}`;
  const language = hasAlternate ? link(alternate, english ? '한국어' : 'English', ` lang="${english ? 'ko' : 'en'}" hreflang="${english ? 'ko' : 'en'}"`) : '';
  const contact = app?.supportEmail ?? site.contactEmail;
  const supportLabel = english ? 'Support' : '고객지원';
  const privacyLabel = english ? 'Privacy' : '개인정보';
  return `<!doctype html>
<!-- Generated by npm run build. Edit apps/, content/, scripts/lib/ instead. -->
<html lang="${locale}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHTML(title)}</title>
  <meta name="description" content="${escapeHTML(description)}">
  <link rel="canonical" href="https://woozy-a.github.io/WoozyLab/${route}">
  ${hasAlternate ? `<link rel="alternate" hreflang="${locale}" href="${url(route)}"><link rel="alternate" hreflang="${english ? 'ko' : 'en'}" href="${url(alternate)}">` : ''}
  <link rel="stylesheet" href="${url('assets/css/site.css')}?v=${cssVersion}">
  <link rel="stylesheet" href="${url('assets/css/themes.css')}?v=${cssVersion}">
  ${app ? `<link rel="icon" href="${url(app.icon)}">` : ''}
</head>
<body class="site-page ${app ? `theme-${app.slug}` : 'home-page'}">
  <a class="skip-link" href="#main">${english ? 'Skip to content' : '본문으로 건너뛰기'}</a>
  <header class="site-header">
    <nav class="site-nav" aria-label="${english ? 'Main navigation' : '주요 메뉴'}">
      <a class="site-brand" href="${url(base)}">WoozyLab<span aria-hidden="true">.</span></a>
      <div class="site-nav-links">${link(base + '#apps', 'Apps')}${link(base + '#web-labs', 'Web Labs')}${link(base + 'support/', 'Support')}${link(base + 'privacy/', 'Privacy')}${link(base + '#contact', 'Contact')}${language}</div>
    </nav>
    ${app ? `<nav class="app-nav" aria-label="${escapeHTML(app.name)} ${english ? 'navigation' : '메뉴'}"><a class="app-nav-name" href="${url(appRoute(app, '', locale))}"><img src="${url(app.icon)}" width="28" height="28" alt="">${escapeHTML(app.name)}</a><div>${link(appRoute(app, '', locale), english ? 'Overview' : '소개')}${link(appRoute(app, 'support', locale), supportLabel)}${link(appRoute(app, 'privacy', locale), privacyLabel)}</div></nav>` : ''}
  </header>
  <main id="main" class="${role === 'support' || role === 'privacy' ? 'document-shell' : 'page-shell'}">${content}</main>
  <footer class="site-footer"><div class="footer-inner"><div><a class="site-brand" href="${url(base)}">WoozyLab.</a><p>© 2026 WoozyLab</p></div><nav class="footer-links" aria-label="${english ? 'Footer navigation' : '푸터 메뉴'}">${link(base + 'support/', 'Support')}${link(base + 'privacy/', 'Privacy Policy')}<a href="mailto:${escapeHTML(contact)}">Contact · ${escapeHTML(contact)}</a></nav></div></footer>
</body>
</html>\n`.replace(/^[ \t]+$/gm, '');
}
