import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { relativeURL, escapeHTML, appRoute } from './lib/layout.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => readFile(path.join(root,file),'utf8');
const json = async file => JSON.parse(await read(file));
const apps = await Promise.all((await readdir(path.join(root,'apps'))).filter(f=>f.endsWith('.json')).map(f=>json('apps/'+f)));
const site = await json('content/site.json');
const documents = await json('content/documents.json');
const provenance = await json('content/document-provenance.json');
const routes = ['', 'support/', 'privacy/', 'en/', 'en/support/', 'en/privacy/', ...apps.flatMap(a=>['','support/','privacy/'].map(role=>a.slug+'/'+role)), 'en/keypic/','en/keypic/support/','en/keypic/privacy/'];

test('Relative paths preserve local previews, nested URLs and anchors',()=>{
  assert.equal(relativeURL('', 'keypic/'), './keypic/');
  assert.equal(relativeURL('keypic/privacy/', ''), '../../');
  assert.equal(relativeURL('en/keypic/privacy/', 'assets/css/site.css'), '../../../assets/css/site.css');
  assert.equal(relativeURL('en/keypic/', 'en/#contact'), '../#contact');
  assert.equal(relativeURL('', '#apps'), './#apps');
  assert.equal(relativeURL('keypic/', 'https://apps.apple.com/abc'), 'https://apps.apple.com/abc');
});
test('Text escaping never emits raw HTML',()=>assert.equal(escapeHTML(`<a x="a&b">'`), '&lt;a x=&quot;a&amp;b&quot;&gt;&#39;'));
test('Only verified English app routes are emitted',()=>{
  assert.equal(appRoute({slug:'keypic'},'privacy','en'),'en/keypic/privacy/');
  assert.equal(appRoute({slug:'glasslingo'},'support','en'),'glasslingo/support/');
  assert.equal(appRoute({slug:'orannamu'},'','en'),'orannamu/');
});
test('Every registered app has exactly one ordering entry',()=>assert.deepEqual([...site.appOrder].sort(), apps.map(a=>a.slug).sort()));

for (const route of routes) test(`Page contract: /${route}`,async()=>{
  const html = await read(route+'index.html');
  assert.match(html,/Generated by npm run build/);
  assert.equal([...html.matchAll(/<h1(?:\s|>)/g)].length,1);
  assert.equal([...html.matchAll(/<main(?:\s|>)/g)].length,1);
  assert.ok(html.includes('id="main"'));
  assert.ok(html.includes('class="skip-link"'));
  assert.match(html,/class="site-header"/);
  assert.match(html,/class="site-footer"/);
  assert.ok(html.includes('assets/css/site.css'));
  assert.ok(html.includes('assets/css/themes.css'));
  assert.ok(!/<style\b|\sstyle=|<script\b/.test(html),'No page-local styling, JS or tracking');
  assert.ok(!/<button\b/.test(html),'Navigation is links, not fake buttons');
  assert.ok(html.includes(`https://woozy-a.github.io/WoozyLab/${route}"`));
  assert.ok(html.includes(`lang="${route.startsWith('en/')?'en':'ko'}"`));
  for (const img of html.matchAll(/<img\b[^>]*>/g)) assert.match(img[0],/alt="[^"]*"/);
  assert.match(html,/href="mailto:[^"\s]+@[^"\s]+"/);
});
for (const record of provenance) test(`Reviewed document body preserved: ${record.route}`,async()=>{
  const body=documents[record.route].body;
  assert.equal(createHash('sha256').update(body).digest('hex'),record.bodySHA256);
  assert.ok((await read(record.route+'index.html')).includes(body));
});
for (const app of apps) test(`Consistent links, copy and contact: ${app.slug}`,async()=>{
  const product = await read(app.slug+'/index.html');
  assert.ok(product.includes(app.summary));
  assert.ok(product.includes(app.status));
  if (!app.appStoreURL) assert.ok(!product.includes('>App Store'));
  for (const role of ['support','privacy']) {
    const html=await read(app.slug+'/'+role+'/index.html');
    assert.ok(html.includes(app.supportEmail));
    const otherEmail=apps.find(a=>a.supportEmail!==app.supportEmail)?.supportEmail;
    if(otherEmail) assert.ok(!html.includes(otherEmail),'Do not route app support to another app contact');
  }
});
test('Orannamu does not market unavailable public AR or visits',async()=>{
  const html=await read('orannamu/index.html');
  assert.ok(!html.includes('현장 AR'));
  assert.ok(!html.includes('방문 인증'));
  assert.ok(html.includes('편집 재구성 이미지'));
  assert.ok(html.includes('실제 당시 사진이 아닙니다'));
});
test('Old Web Lab and GlassLingo section anchors survive',async()=>{
  for(const route of ['','en/']) assert.ok((await read(route+'index.html')).includes(site.webLab.url));
  const html=await read('glasslingo/index.html');
  for(const id of ['glasslingo','support','privacy']) assert.ok(html.includes(`id="${id}"`));
});
test('Common style supports wrapping, focus, readable text and reduced motion',async()=>{
  const css=await read('assets/css/site.css');
  for(const rule of ['font-size: 16px','focus-visible','prefers-reduced-motion','prefers-color-scheme: dark','flex-wrap: wrap','max-width: 640px']) assert.ok(css.includes(rule));
  assert.ok(!css.includes('overflow-x: hidden'),'Do not hide overflow to mask layout errors');
});
